version: '3'

services:
  db-mysql:
    image: mysql:5.6
    container_name: db-mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3307:3306"
    restart: unless-stopped

  kaddem-project-app:
    image: seifbenkarim/kaddem-project
    restart: unless-stopped
    ports:
      - 8089:8089
    depends_on:
      - db-mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/kaddem\db?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root