db-mysql:
  image: mysql:5.6
  container_name: db-mysql
  environment:
    - MYSQL_ROOT_PASSWORD: "root"
  ports:
    - "3307:3306"
  restart: unless-stopped

kaddem:
  image: houssem-docker
  restart: unless-stopped
  ports:
    - 8089:8089
  depends_on:
    - db-mysql
  environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/kaddem\db?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    - SPRING_DATASOURCE_USERNAME=root
    - SPRING_DATASOURCE_PASSWORD=root